# Generated by Django 3.2.9 on 2021-12-04 07:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0002_address_city_country'),
        ('baskets', '0002_basketitem'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('modified_at', models.DateTimeField(auto_now=True, verbose_name='Modified at')),
                ('billing_address', models.CharField(max_length=255, verbose_name='Billing Address')),
                ('shipping_address', models.CharField(max_length=255, verbose_name='Shipping Address')),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Total Price')),
                ('basket', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='baskets.basket', verbose_name='Basket')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Customer')),
            ],
            options={
                'verbose_name': 'order',
                'verbose_name_plural': 'orders',
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('modified_at', models.DateTimeField(auto_now=True, verbose_name='Modified at')),
                ('product', models.CharField(max_length=255, verbose_name='Product')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Price')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='orders.order', verbose_name='Order')),
            ],
            options={
                'verbose_name': 'orderItem',
                'verbose_name_plural': 'orderItems',
            },
        ),
        migrations.CreateModel(
            name='OrderBankAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('modified_at', models.DateTimeField(auto_now=True, verbose_name='Modified at')),
                ('bank_name', models.CharField(max_length=50, verbose_name='Bank Name')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('iban', models.CharField(max_length=50, verbose_name='Iban')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='orders.order', verbose_name='Order')),
            ],
            options={
                'verbose_name': 'orderBankAccount',
                'verbose_name_plural': 'orderBankAccounts',
            },
        ),
        migrations.CreateModel(
            name='InvoiceAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('modified_at', models.DateTimeField(auto_now=True, verbose_name='Modified at')),
                ('full_name', models.CharField(max_length=50, verbose_name='Full Name')),
                ('line1', models.CharField(max_length=255, verbose_name='Line 1')),
                ('line2', models.CharField(max_length=255, verbose_name='Line 2')),
                ('phone', models.CharField(max_length=20, verbose_name='Phone')),
                ('district', models.CharField(max_length=25, verbose_name='District')),
                ('postcode', models.CharField(max_length=10, verbose_name='Postcode')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='customers.city', verbose_name='City')),
            ],
            options={
                'verbose_name': 'invoiceAddress',
                'verbose_name_plural': 'invoiceAddresses',
            },
        ),
        migrations.CreateModel(
            name='BillingAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('modified_at', models.DateTimeField(auto_now=True, verbose_name='Modified at')),
                ('full_name', models.CharField(max_length=50, verbose_name='Full Name')),
                ('line1', models.CharField(max_length=255, verbose_name='Line 1')),
                ('line2', models.CharField(max_length=255, verbose_name='Line 2')),
                ('phone', models.CharField(max_length=20, verbose_name='Phone')),
                ('district', models.CharField(max_length=25, verbose_name='District')),
                ('postcode', models.CharField(max_length=10, verbose_name='Postcode')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='customers.city', verbose_name='City')),
            ],
            options={
                'verbose_name': 'billingAddress',
                'verbose_name_plural': 'billingAddresses',
            },
        ),
    ]
