# Generated by Django 3.2.9 on 2021-12-03 20:08

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='billingaddress',
            options={'verbose_name': 'billing address', 'verbose_name_plural': 'billing addresses'},
        ),
        migrations.AlterModelOptions(
            name='order',
            options={'verbose_name': 'order', 'verbose_name_plural': 'orders'},
        ),
        migrations.AlterModelOptions(
            name='orderbankaccount',
            options={'verbose_name': 'order bank account', 'verbose_name_plural': 'order bank accounts'},
        ),
        migrations.AlterModelOptions(
            name='orderitem',
            options={'verbose_name': 'order item', 'verbose_name_plural': 'order items'},
        ),
        migrations.AlterModelOptions(
            name='shippingaddress',
            options={'verbose_name': 'shipping address', 'verbose_name_plural': 'shipping addresses'},
        ),
        migrations.AddField(
            model_name='billingaddress',
            name='phone',
            field=models.CharField(max_length=15, null=True, validators=[django.core.validators.RegexValidator(message="Tel Number must be entered in the format: '09012345678'. Up to 15 digits allowed.", regex='^[0-9]+$')], verbose_name='phone'),
        ),
        migrations.AddField(
            model_name='shippingaddress',
            name='phone',
            field=models.CharField(max_length=15, null=True, validators=[django.core.validators.RegexValidator(message="Tel Number must be entered in the format: '09012345678'. Up to 15 digits allowed.", regex='^[0-9]+$')], verbose_name='phone'),
        ),
        migrations.AlterField(
            model_name='billingaddress',
            name='postcode',
            field=models.CharField(max_length=7, validators=[django.core.validators.RegexValidator(message="Postal Code must be entered in the format: '1234567'. Up to 7 digits allowed.", regex='^[0-9]+$')], verbose_name='Postal code'),
        ),
        migrations.AlterField(
            model_name='orderbankaccount',
            name='bank_name',
            field=models.CharField(max_length=75, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='orderbankaccount',
            name='iban',
            field=models.CharField(max_length=34),
        ),
        migrations.AlterField(
            model_name='shippingaddress',
            name='postcode',
            field=models.CharField(max_length=7, validators=[django.core.validators.RegexValidator(message="Postal Code must be entered in the format: '1234567'. Up to 7 digits allowed.", regex='^[0-9]+$')], verbose_name='Postal code'),
        ),
    ]
