# Generated by Django 3.2.9 on 2021-12-03 02:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='invoiceaddress',
            options={'verbose_name': 'Invoice Address', 'verbose_name_plural': 'Invoice Addresses'},
        ),
    ]
