# Generated by Django 3.2.9 on 2021-12-04 08:17

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billingaddress',
            name='phone',
            field=models.CharField(max_length=16, validators=[django.core.validators.RegexValidator(message="You have entered an invalid phone number. Please try again. Example: '05231231212', '0523 123 12 12'", regex='/^(05)([0-9]{2})\\s?([0-9]{3})\\s?([0-9]{2})\\s?([0-9]{2})$/')], verbose_name='Phone Number'),
        ),
        migrations.AlterField(
            model_name='orderbankaccount',
            name='iban',
            field=models.CharField(max_length=30, validators=[django.core.validators.RegexValidator(message='You have entered an IBAN', regex='\\b[A-Z]{2}[0-9]{2}(?:[ ]?[0-9]{4}){4}(?!(?:[ ]?[0-9]){3})(?:[ ]?[0-9]{1,2})?\\b')], verbose_name='IBAN Number'),
        ),
        migrations.AlterField(
            model_name='shippingaddress',
            name='phone',
            field=models.CharField(max_length=16, validators=[django.core.validators.RegexValidator(message="You have entered an invalid phone number. Please try again. Example: '05231231212', '0523 123 12 12'", regex='/^(05)([0-9]{2})\\s?([0-9]{3})\\s?([0-9]{2})\\s?([0-9]{2})$/')], verbose_name='Phone Number'),
        ),
    ]
