# Generated by Django 3.2.9 on 2021-12-04 08:23

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_alter_billingaddress_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='billingaddress',
            name='post_code',
            field=models.CharField(max_length=5, validators=[django.core.validators.RegexValidator(message="postcode must be entered in the format: '99999'.", regex='\\d{5}')]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='shippingaddress',
            name='post_code',
            field=models.CharField(default='fa', max_length=5, validators=[django.core.validators.RegexValidator(message="postcode must be entered in the format: '99999'.", regex='\\d{5}')]),
            preserve_default=False,
        ),
    ]
