# Generated by Django 3.2.9 on 2021-12-04 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_auto_20211204_1123'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billingaddress',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='shippingaddress',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Name'),
        ),
    ]
