# Generated by Django 3.2.9 on 2021-12-04 08:01

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bankaccount',
            name='iban',
            field=models.CharField(max_length=50, validators=[django.core.validators.RegexValidator(message='Enter a valid IBAN number.', regex='^[A-Z]{2}[0-9]{2}[A-Z0-9]{4}[0-9]{7}([A-Z0-9]?){0,16}$')], verbose_name='IBAN'),
        ),
    ]
