# Generated by Django 3.2.9 on 2021-12-01 16:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bankaccount',
            options={'verbose_name': 'account', 'verbose_name_plural': 'accounts'},
        ),
    ]
