# Generated by Django 3.2.9 on 2021-12-04 06:43

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bankaccount',
            name='iban',
            field=models.CharField(max_length=27, validators=[django.core.validators.RegexValidator(message="iban must be entered in the format: '9999999999999999999999'\n or in the format: '9999 9999 9999 9999 9999 99'. ", regex='\\b[A-Z]{2}[0-9]{2}(?:[ ]?[0-9]{4}){4}(?!(?:[ ]?[0-9]){3})(?:[ ]?[0-9]{1,2})?\\b')]),
            preserve_default=False,
        ),
    ]
