# Generated by Django 3.2.9 on 2021-12-04 07:21

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0004_alter_bankaccount_iban'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bankaccount',
            name='iban',
            field=models.CharField(max_length=34, validators=[django.core.validators.RegexValidator(message='Enter your IBAN (without spaces) in the appropriate format.', regex='/^[A-Z]{2}[a-zA-Z0-9]{10,34}$')], verbose_name='IBAN'),
        ),
    ]
