# Generated by Django 3.2.9 on 2021-12-02 12:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('baskets', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='basketitem',
            options={'verbose_name': 'basket item', 'verbose_name_plural': 'Basket Items'},
        ),
    ]
