# Generated by Django 3.2.9 on 2021-12-23 18:36
import uuid
from django.db import migrations


def forwards(apps, schema_editor):
    Basket = apps.get_model('baskets', 'Basket')
    for basket in Basket.objects.all():
        basket.slug = uuid.uuid4()
        basket.save(update_fields=['slug'])


class Migration(migrations.Migration):

    dependencies = [
        ('baskets', '0003_basket_slug'),
    ]

    operations = [
        migrations.RunPython(forwards)
    ]
