# Generated by Django 3.2.9 on 2021-12-05 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0003_auto_20211203_1919"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="categories",
            field=models.ManyToManyField(
                to="products.Category", verbose_name="Categories"
            ),
        ),
    ]
