# Generated by Django 3.2.9 on 2021-12-03 11:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('name', models.CharField(max_length=56, verbose_name='name')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('name', models.CharField(max_length=35, verbose_name='name')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='customers.country')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('name', models.CharField(max_length=100, verbose_name='name')),
                ('full_name', models.CharField(max_length=200, verbose_name='full name')),
                ('line1', models.CharField(max_length=250, verbose_name='line1')),
                ('line2', models.CharField(max_length=250, verbose_name='line2')),
                ('district', models.CharField(max_length=100, verbose_name='district')),
                ('postcode', models.CharField(max_length=25, verbose_name='postcode')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='customers.city')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='customer',
            name='addresses',
            field=models.ManyToManyField(to='customers.Address'),
        ),
    ]
