# Generated by Django 3.2.9 on 2021-12-04 07:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('modified_at', models.DateTimeField(auto_now=True, verbose_name='Modified at')),
                ('full_name', models.CharField(max_length=255, verbose_name='Full Name')),
                ('line_1', models.CharField(max_length=255, verbose_name='Address Line 1')),
                ('line_2', models.CharField(max_length=255, verbose_name='Address Line 2')),
                ('phone', models.CharField(max_length=16, verbose_name='Phone Number')),
                ('district', models.CharField(max_length=255, verbose_name='District')),
                ('postcode', models.CharField(max_length=10, verbose_name='Post Code')),
                ('address_type', models.CharField(choices=[('BI', 'Billing'), ('SH', 'Shipping'), ('BS', 'Billing & Shipping')], default='BS', max_length=2)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.city', verbose_name='City')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Address',
                'verbose_name_plural': 'Addresses',
            },
        ),
    ]
