# Generated by Django 3.2.9 on 2021-12-03 18:56

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('modified_at', models.DateTimeField(auto_now=True, verbose_name='Modified at')),
                ('name', models.CharField(max_length=45, verbose_name='Country')),
            ],
            options={
                'verbose_name_plural': 'countries',
            },
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('modified_at', models.DateTimeField(auto_now=True, verbose_name='Modified at')),
                ('name', models.CharField(max_length=55, verbose_name='City')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customers.country')),
            ],
            options={
                'verbose_name_plural': 'cities',
            },
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('modified_at', models.DateTimeField(auto_now=True, verbose_name='Modified at')),
                ('title', models.CharField(choices=[('home', 'Home'), ('work', 'Work'), ('other', 'Other')], max_length=20, verbose_name='Address Title')),
                ('full_name', models.CharField(max_length=255, verbose_name='First Name')),
                ('line1', models.CharField(max_length=200, verbose_name='Address Line1')),
                ('line2', models.CharField(blank=True, max_length=200, verbose_name='Address Line2')),
                ('phone_number', models.CharField(blank=True, max_length=17, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')], verbose_name='Phone Number')),
                ('district', models.CharField(blank=True, max_length=40, verbose_name='District')),
                ('postal_code', models.CharField(max_length=12, verbose_name='Postal Code')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='customers.country', verbose_name='City')),
            ],
            options={
                'verbose_name_plural': 'Addresses',
                'unique_together': {('line1', 'line2', 'postal_code', 'city', 'district')},
            },
        ),
    ]
