# Generated by Django 3.2.9 on 2021-12-04 10:20

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0002_city_country'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('fullname', models.CharField(max_length=255, verbose_name='fullname')),
                ('address1', models.CharField(max_length=1024, verbose_name='Address line 1')),
                ('address2', models.CharField(max_length=1024, verbose_name='Address line 2')),
                ('phone', models.CharField(max_length=16, validators=[django.core.validators.RegexValidator(message='Phone number must be entered as all numericin the format 05555555555up to 16 digits', regex='^[0-9]+$')], verbose_name='phone')),
                ('name', models.CharField(max_length=127, verbose_name='district')),
                ('postcode', models.CharField(max_length=10, validators=[django.core.validators.RegexValidator(message='Postcode must be entered as all numeric up to 10 digits 0123456789', regex='^[0-9]+$')], verbose_name='postcode')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='customers.city', verbose_name='City')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
