# Generated by Django 3.2.9 on 2021-12-03 17:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("customers", "0002_address_city_country"),
    ]

    operations = [
        migrations.AlterField(
            model_name="address",
            name="city",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to="customers.city",
                verbose_name="City",
            ),
        ),
        migrations.AlterField(
            model_name="city",
            name="country",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to="customers.country",
                verbose_name="Country",
            ),
        ),
    ]
