# Generated by Django 3.2.9 on 2021-12-05 01:37

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0002_address_city_country'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='city',
            name='last_login',
        ),
        migrations.RemoveField(
            model_name='city',
            name='password',
        ),
        migrations.AddField(
            model_name='city',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Created at'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='city',
            name='modified_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Modified at'),
        ),
    ]
