# Generated by Django 3.2.9 on 2021-11-30 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0002_address_city_country'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='post_code',
            field=models.IntegerField(verbose_name='Post Code'),
        ),
    ]
