# Generated by Django 3.2.9 on 2021-12-04 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0002_address_city_country'),
    ]

    operations = [
        migrations.RenameField(
            model_name='address',
            old_name='fullname',
            new_name='full_name',
        ),
        migrations.RenameField(
            model_name='address',
            old_name='line1',
            new_name='line_1',
        ),
        migrations.RenameField(
            model_name='address',
            old_name='line2',
            new_name='line_2',
        ),
        migrations.RenameField(
            model_name='address',
            old_name='postcode',
            new_name='post_code',
        ),
        migrations.AddField(
            model_name='address',
            name='district',
            field=models.CharField(default=0, max_length=100, verbose_name='District'),
            preserve_default=False,
        ),
    ]
