# Generated by Django 3.2.9 on 2021-12-04 08:17

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0003_address_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='phone',
            field=models.CharField(max_length=16, validators=[django.core.validators.RegexValidator(message="You have entered an invalid phone number. Please try again. Example: '05231231212', '0523 123 12 12'", regex='/^(05)([0-9]{2})\\s?([0-9]{3})\\s?([0-9]{2})\\s?([0-9]{2})$/')], verbose_name='Phone Number'),
        ),
    ]
