# Generated by Django 3.2.9 on 2021-12-04 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("customers", "0003_auto_20211203_2031"),
    ]

    operations = [
        migrations.AlterField(
            model_name="address",
            name="district",
            field=models.CharField(max_length=255, verbose_name="District"),
        ),
    ]
