# Generated by Django 3.2.9 on 2021-12-04 15:47

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0003_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='district',
            field=models.CharField(default=django.utils.timezone.now, max_length=127, verbose_name='district'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='address',
            name='name',
            field=models.CharField(max_length=127, verbose_name='name'),
        ),
    ]
