# Generated by Django 3.2.9 on 2021-12-02 15:01

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0003_alter_address_city'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='address',
            options={'ordering': ['name'], 'verbose_name': 'address', 'verbose_name_plural': 'addresses'},
        ),
        migrations.AlterModelOptions(
            name='city',
            options={'verbose_name': 'city', 'verbose_name_plural': 'cities'},
        ),
        migrations.AlterModelOptions(
            name='country',
            options={'verbose_name': 'country', 'verbose_name_plural': 'countries'},
        ),
        migrations.AlterModelOptions(
            name='customer',
            options={'verbose_name': 'Customer', 'verbose_name_plural': 'Customers'},
        ),
        migrations.AddField(
            model_name='address',
            name='post_code',
            field=models.CharField(max_length=11, null=True, validators=[django.core.validators.RegexValidator(message='Enter a valid post/zip code', regex='(?i)^[a-z0-9][a-z0-9\\- ]{0,10}[a-z0-9]$')], verbose_name='Post Code'),
        ),
    ]
